#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnetfilter_acct
Version  : 1.0.2
Release  : 1
URL      : https://github.com/Distrotech/libnetfilter_acct/archive/distrotech-libnetfilter_acct-1.0.2.tar.gz
Source0  : https://github.com/Distrotech/libnetfilter_acct/archive/distrotech-libnetfilter_acct-1.0.2.tar.gz
Summary  : Netfilter extended accounting infrastructure library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libnetfilter_acct-lib = %{version}-%{release}
BuildRequires : pkgconfig(libmnl)

%description
= nfacct: the extended accounting infrastructure for Netfilter =
Netfilter provides three accounting mechanisms:

%package dev
Summary: dev components for the libnetfilter_acct package.
Group: Development
Requires: libnetfilter_acct-lib = %{version}-%{release}
Provides: libnetfilter_acct-devel = %{version}-%{release}

%description dev
dev components for the libnetfilter_acct package.


%package lib
Summary: lib components for the libnetfilter_acct package.
Group: Libraries

%description lib
lib components for the libnetfilter_acct package.


%prep
%setup -q -n libnetfilter_acct-distrotech-libnetfilter_acct-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547159410
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1547159410
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_acct/libnetfilter_acct.h
/usr/lib64/libnetfilter_acct.so
/usr/lib64/pkgconfig/libnetfilter_acct.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetfilter_acct.so.1
/usr/lib64/libnetfilter_acct.so.1.0.0
